// ============================================
// Demo data for development without Supabase
// ============================================

import type { Guest, Party } from "./database.types";

export const DEMO_PARTIES: Party[] = [
  {
    id: "party-1",
    party_name: "The Smith Family",
    max_guests: 3,
    address: "123 Main St, Dallas, TX",
    invite_sent: true,
    invite_sent_date: "2026-03-01",
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "party-2",
    party_name: "Johnson Party",
    max_guests: 2,
    address: "456 Oak Ave, Houston, TX",
    invite_sent: true,
    invite_sent_date: "2026-03-01",
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "party-3",
    party_name: "Emily Davis",
    max_guests: 1,
    address: "789 Elm Blvd, Austin, TX",
    invite_sent: true,
    invite_sent_date: "2026-03-01",
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "party-4",
    party_name: "The Williams Family",
    max_guests: 4,
    address: "321 Pine Dr, San Antonio, TX",
    invite_sent: false,
    invite_sent_date: null,
    created_at: "2026-01-15T00:00:00Z",
  },
];

export const DEMO_GUESTS: Guest[] = [
  {
    id: "guest-1",
    first_name: "John",
    last_name: "Smith",
    email: "john@example.com",
    party_id: "party-1",
    rsvp_status: "pending",
    meal_choice: null,
    dietary_restrictions: null,
    notes: null,
    responded_at: null,
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "guest-2",
    first_name: "Jane",
    last_name: "Smith",
    email: null,
    party_id: "party-1",
    rsvp_status: "pending",
    meal_choice: null,
    dietary_restrictions: null,
    notes: null,
    responded_at: null,
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "guest-3",
    first_name: "Tommy",
    last_name: "Smith",
    email: null,
    party_id: "party-1",
    rsvp_status: "pending",
    meal_choice: null,
    dietary_restrictions: null,
    notes: null,
    responded_at: null,
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "guest-4",
    first_name: "Mike",
    last_name: "Johnson",
    email: "mike@example.com",
    party_id: "party-2",
    rsvp_status: "accepted",
    meal_choice: "Beef",
    dietary_restrictions: null,
    notes: "So excited!",
    responded_at: "2026-04-10T00:00:00Z",
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "guest-5",
    first_name: "Sarah",
    last_name: "Johnson",
    email: null,
    party_id: "party-2",
    rsvp_status: "accepted",
    meal_choice: "Salmon",
    dietary_restrictions: "Gluten-free",
    notes: null,
    responded_at: "2026-04-10T00:00:00Z",
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "guest-6",
    first_name: "Emily",
    last_name: "Davis",
    email: "emily@example.com",
    party_id: "party-3",
    rsvp_status: "declined",
    meal_choice: null,
    dietary_restrictions: null,
    notes: "So sorry to miss it — will be traveling abroad!",
    responded_at: "2026-04-15T00:00:00Z",
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "guest-7",
    first_name: "Robert",
    last_name: "Williams",
    email: "robert@example.com",
    party_id: "party-4",
    rsvp_status: "pending",
    meal_choice: null,
    dietary_restrictions: null,
    notes: null,
    responded_at: null,
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "guest-8",
    first_name: "Lisa",
    last_name: "Williams",
    email: null,
    party_id: "party-4",
    rsvp_status: "pending",
    meal_choice: null,
    dietary_restrictions: null,
    notes: null,
    responded_at: null,
    created_at: "2026-01-15T00:00:00Z",
  },
];
